### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by samuelba** [facebook/fbshipit#68]
I cannot build fbshipit because of the following error:

Composer version 1.8.4 2019-02-11 10:52:10
fbshipit: master
hhvm: 4.0.3-1~bionic

```
hhvm /usr/local/bin/composer require facebook/fbshipit

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'array_pop() expects parameter 1 by reference, but the call was not annotated with '&'' in phar://composer.phar/bin/../src/../src/Composer/Util/Silencer.php:51
Stack trace:
#0 phar://composer.phar/bin/../src/../src/Composer/Util/Silencer.php(74): Composer\Util\Silencer::restore()
#1 phar://composer.phar/bin/../src/../src/Composer/Console/Application.php(73): Composer\Util\Silencer::call()
#2 phar://composer.phar/bin/composer(55): Composer\Console\Application->__construct()
#3 /usr/local/bin/composer(24): include()
#4 {main}
```

Will this be fixed? Or is there a solution for this problem? Or is fbshipit dead?

**Comment by mikegerber** [comment]
It seems like you have to call Composer using PHP since they dropped support for HHVM (and the README is wrong now.)

**Comment by bigfootjon** [comment]
This was fixed in https://github.com/facebook/fbshipit/commit/ece3eb53de5027f7f16aa4e1bc353a770fe398cf
